DefaultContentLanguage = "en"
baseURL = "http://freshmusicspam.com"
enableRobotsTXT = true
googleAnalytics = "UA-133748370-1"
languageCode = "en-us"
theme = "ananke"
title = "Fresh Music Spam"
[params]
background_color_class = "bg-black"
description = "You've seen it everywhere else, why not here?"
facebook = ""
favicon = ""
github = ""
gitlab = ""
instagram = ""
linkedin = ""
recent_posts_number = 5
twitter = "https://twitter.com/freshmusicspam"
youtube = ""
[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5
